# ------------------------------------------------------------------------------
# platformio_override.ini to activate overrides
# ------------------------------------------------------------------------------

[platformio]
default_envs = m5stack_cores3

[env:m5stack_cores3]
extends = env:esp32s3dev_16MB_opi

custom_usermods =
    CoreS3_Power

build_flags =
    ${env:esp32s3dev_16MB_opi.build_flags}
    -D I2CSDAPIN=12
    -D I2CSCLPIN=11
